# capi/cmake/gen_export_list.cmake — generate an export-restriction file for
# the C API. Invoked by capi/CMakeLists.txt.
#
#   cmake -DNM=<nm-tool> [-DNM_FLAGS=<flags>] -DOBJS=<obj;...> -DOUT=<file>
#         [-DDEF_FILE=1] -P <this script>
#
# Lists every defined mdac_* symbol in the objects, and nothing else. The list
# comes from the compiled objects, not from miradac.h, because most of the API
# is declared there through macros.
#
# Default (Apple): an ld -exported_symbols_list file, one _mdac_* per line
# (Mach-O leading underscore): linking with it hides everything not listed,
# reproducing the GNU version script's `global: mdac_*; local: *`.
#
# With DEF_FILE=1 (MinGW): an ld .def file. Passing it to MinGW ld replaces
# the PE export-everything fallback with exactly the listed names — the same
# contract.

if(NOT NM OR NOT OBJS OR NOT OUT)
    message(FATAL_ERROR "gen_export_list: set -DNM, -DOBJS and -DOUT")
endif()

# -U (defined symbols only) is the Apple cctools and llvm-nm spelling; GNU nm
# spells it --defined-only. The caller knows which nm it found.
set(_nm_flags -U)
if(DEFINED NM_FLAGS)
    separate_arguments(_nm_flags NATIVE_COMMAND "${NM_FLAGS}")
endif()

execute_process(COMMAND ${NM} ${_nm_flags} ${OBJS}
                OUTPUT_VARIABLE _nm_out RESULT_VARIABLE _nm_rc)
if(NOT _nm_rc EQUAL 0)
    message(FATAL_ERROR "gen_export_list: nm failed (${_nm_rc})")
endif()

set(_syms)
string(REPLACE "\n" ";" _lines "${_nm_out}")
foreach(_line IN LISTS _lines)
    # nm form: "0000000000000000 T _mdac_init" (Mach-O, and i686 PE where C
    # symbols carry a leading underscore) or "... T mdac_init" (ELF and
    # x86_64 PE). Archive-member headers and undefined symbols do not match.
    if(_line MATCHES "^[0-9a-fA-F]+[ \t]+[A-Za-z][ \t]+_?(mdac_[A-Za-z0-9_]+)$")
        if(DEF_FILE)
            # Plain names: MinGW ld matches a .def name against the object
            # symbol table with or without the i686 leading underscore.
            list(APPEND _syms "${CMAKE_MATCH_1}")
        else()
            list(APPEND _syms "_${CMAKE_MATCH_1}")
        endif()
    endif()
endforeach()
list(SORT _syms)
list(REMOVE_DUPLICATES _syms)
if(NOT _syms)
    message(FATAL_ERROR "gen_export_list: no mdac_* symbols defined in the objects")
endif()
string(REPLACE ";" "\n" _syms "${_syms}")
if(DEF_FILE)
    # `;` starts a comment in a .def file.
    file(WRITE "${OUT}"
        "; Generated by capi/cmake/gen_export_list.cmake — do not edit.\nEXPORTS\n${_syms}\n")
else()
    file(WRITE "${OUT}" "# Generated by capi/cmake/gen_export_list.cmake — do not edit.\n${_syms}\n")
endif()
