# capi/cmake/gen_export_list.cmake — generate an Apple ld
# -exported_symbols_list file for the C API. Invoked by capi/CMakeLists.txt.
#
#   cmake -DNM=<nm-tool> -DOBJS=<obj;...> -DOUT=<file> -P <this script>
#
# Lists every defined mdac_* symbol in the objects, with the Mach-O leading
# underscore, and nothing else: linking with -exported_symbols_list then hides
# everything not listed, reproducing the GNU version script's
# `global: mdac_*; local: *`. The list comes from the compiled objects, not
# from miradac.h, because most of the API is declared there through macros.

if(NOT NM OR NOT OBJS OR NOT OUT)
    message(FATAL_ERROR "gen_export_list: set -DNM, -DOBJS and -DOUT")
endif()

execute_process(COMMAND ${NM} -U ${OBJS}
                OUTPUT_VARIABLE _nm_out RESULT_VARIABLE _nm_rc)
if(NOT _nm_rc EQUAL 0)
    message(FATAL_ERROR "gen_export_list: nm failed (${_nm_rc})")
endif()

set(_syms)
string(REPLACE "\n" ";" _lines "${_nm_out}")
foreach(_line IN LISTS _lines)
    # nm form: "0000000000000000 T _mdac_init" (Mach-O) or "... T mdac_init" (ELF).
    # -U (defined symbols only) works on GNU nm, llvm-nm and Apple cctools nm.
    # Archive-member headers and undefined symbols do not match.
    if(_line MATCHES "^[0-9a-fA-F]+[ \t]+[A-Za-z][ \t]+_?(mdac_[A-Za-z0-9_]+)$")
        list(APPEND _syms "_${CMAKE_MATCH_1}")
    endif()
endforeach()
list(SORT _syms)
list(REMOVE_DUPLICATES _syms)
if(NOT _syms)
    message(FATAL_ERROR "gen_export_list: no mdac_* symbols defined in the objects")
endif()
string(REPLACE ";" "\n" _syms "${_syms}")
file(WRITE "${OUT}" "# Generated by capi/cmake/gen_export_list.cmake — do not edit.\n${_syms}\n")
